<?php

namespace AppBundle\Repository;

/**
 * CategoryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CategoryRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBlogCategories()
    {
        return $this
            ->getEntityManager()
            ->createQuery("
                SELECT c.slug, c.name, (SELECT COUNT(p.id) FROM AppBundle:Post p WHERE p.category = c.id) AS amount
                FROM AppBundle:Category c
                HAVING amount > 0  
                ORDER BY amount DESC
            ")
            ->setMaxResults(5)
            ->getResult();
    }
}