<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPostComments($postId)
    {
        $query = $this->createQueryBuilder('c')
            ->addSelect('u')
            ->innerJoin('c.user', 'u')
            ->where('c.post = :postId')
            ->setParameter('postId', $postId)
            ->getQuery()
        ;

        return $query->getResult();
    }
}
