<?php

namespace AppBundle\Repository;

/**
 * CommentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentRepository extends \Doctrine\ORM\EntityRepository
{
    public function getPostComments($postId)
    {
        return $this->getEntityManager()->createQuery("
            SELECT c, u
            FROM AppBundle:Comment c
            LEFT JOIN c.user u
            WHERE c.post = :postId
            ORDER BY c.createdAt DESC
        ")->setParameter('postId', $postId)->getResult();
    }
}
