<?php

namespace AppBundle\Repository;

/**
 * PostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PostRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBlogPosts()
    {
        return $this->getEntityManager()->createQuery("
            SELECT p, u, c, t
            FROM AppBundle:Post p
            LEFT JOIN p.user u
            LEFT JOIN p.category c
            LEFT JOIN p.tags t
            ORDER BY p.datetime DESC
        ")->getResult();
    }

    public function getPostsWithCategory($slug)
    {
        return $this->getEntityManager()->createQuery("
            SELECT p, u, c, t
            FROM AppBundle:Post p
            LEFT JOIN p.user u
            LEFT JOIN p.category c
            LEFT JOIN p.tags t
            WHERE c.slug = :slug
            ORDER BY p.datetime DESC
        ")->setParameter('slug', $slug)->getResult();
    }

    public function getPostsWithTag($slug)
    {
        return $this->getEntityManager()->createQuery("
            SELECT p
            FROM AppBundle:Post p
            LEFT JOIN p.user u
            LEFT JOIN p.category c
            LEFT JOIN p.tags t
            WHERE t.slug = :slug
        ")->setParameter('slug', $slug)->getResult();
    }

    public function getPostsByDate($year, $month)
    {
        return $this->getEntityManager()->createQuery("
            SELECT p, u, c, t
            FROM AppBundle:Post p
            LEFT JOIN p.user u
            LEFT JOIN p.category c
            LEFT JOIN p.tags t
            WHERE YEAR(p.datetime) = :year AND MONTH(p.datetime) = :month
            ORDER BY p.datetime DESC
        ")->setParameters([
            'year'  => $year,
            'month' => $month
        ])->getResult();
    }

    public function getArchive()
    {
        return $this->getEntityManager()->createQuery("
            SELECT DISTINCT YEAR(p.datetime) AS year, MONTH(p.datetime) AS month
            FROM AppBundle:Post p
            ORDER BY year DESC, month DESC
        ")->getResult();
    }

    public function getDashboardPosts()
    {
        return $this->getEntityManager()->createQuery("
            SELECT p, u
            FROM AppBundle:Post p
            LEFT JOIN p.user u
            ORDER BY p.datetime DESC
        ")->getResult();
    }
}