<?php

namespace AppBundle\Repository;

/**
 * TagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagRepository extends \Doctrine\ORM\EntityRepository
{
    public function getBlogTags()
    {
        return $this->getEntityManager()->createQuery("
            SELECT t.slug, t.name, COUNT(p) AS amount
            FROM AppBundle:Tag t
            JOIN t.posts p
            GROUP BY t.id
            ORDER BY amount DESC
        ")->getResult();
    }
}
