security:
    encoders:
        AppBundle\Entity\User: bcrypt
    providers:
        database:
            entity:
                class: AppBundle\User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                login_path: blog.signin
                check_path: blog.signin
            logout:
                path: /signout
                target: blog.index
    access_control:
        - { path: ^/dashboard, roles: ROLE_ADMINISTRATOR }