security:
    encoders:
        AppBundle\Entity\User: bcrypt
    providers:
        database:
            entity:
                class: AppBundle:User
                property: email
    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        main:
            anonymous: ~
            form_login:
                check_path: blog.signin
                login_path: blog.signin
                default_target_path: blog.index
            logout:
                path: /signout
                target: blog.index
    access_control:
        - { path: ^/signin$, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/dashboard$, roles: ROLE_ADMINISTRATOR }